services:
  pg_db:
    container_name: ticket_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "my-crm"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
volumes:
  pgdata: {}

