services:
  pg_db:
    container_name: ticket_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "my-crm"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  Etcd:
    image: 'bitnami/etcd:3.5.15'
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_ENABLE_V2=true
    ports:
      - 2379:2379
      - 2380:2380

volumes:
  pgdata: {}
