version: '3.9'

services:
  db:
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tickets
    volumes:
      - postgres_data:/var/lib/postgresql/data
    image: postgres:16.1-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d tickets" ]
      interval: 15s
      timeout: 10s
      retries: 7
      start_period: 12s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4GB

  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd
    command: etcd --advertise-client-urls=http://etcd:2379 --listen-client-urls=http://0.0.0.0:2379
    ports:
      - "2379:2379"
    volumes:
      - etcd_data:/etcd-data

volumes:
  postgres_data:
  etcd_data:
