spring:
  application:
    name: ticket-server
  main:
    web-application-type: none
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  etcd:
    client:
      endpoints:
        - http://127.0.0.1:2379
server:
  port: 8090