ALTER TABLE users
  ALTER COLUMN full_name SET NOT NULL,
  ALTER COLUMN email SET NOT NULL,
  ALTER COLUMN login SET NOT NULL,
  ALTER COLUMN password SET NOT NULL,
  ALTER COLUMN created_at SET NOT NULL,
  ALTER COLUMN created_by SET NOT NULL,
  ALTER COLUMN updated_at SET NOT NULL,
  ALTER COLUMN active SET NOT NULL;